### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by nikgraf** [ReasonVienna/reason-conf-2019#68]
- [x] Startpage copy https://github.com/ReasonVienna/reason-conf-2019/pull/63
- [x] Add CFP link and update CFP to only include name & email https://github.com/ReasonVienna/reason-conf-2019/pull/66
- [x] Add Discord chat https://github.com/ReasonVienna/reason-conf-2019/pull/67
- [x] Turn off test mode in Tito @nikgraf 
- [x] Verify Google Analytics Work @nikgraf 
- [x] Update Twitter Logo for @reasonconf
- [x] Prepare launch tweet

Post Launch

- [x] Send out email to the mailing list
- [x] Announce on FB
